[package]
name = "codegen"
version = "0.1.0"
authors = ["tarberd <bernardo.mferrari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hir = { path = "../hir" }
inkwell = { version = "=0.1.0-beta.2", features = ["llvm11-0"]}
